### PR TITLE
Fixes product add and readme

### PR DESCRIPTION
**Pull request by c0g1t8**
Adding product doesn't work.  This PR fixes a minor bug in _ProductPost.cs_ in the _api_ project.

### CODE REVIEW

**Review by M-Yankov — CHANGES_REQUESTED** [review]
But in that way, the edit is not working. I suggest in ProductDetails.razor Save method to be updated too:

```c#
if (product.Id == 0)
{
    await http.PostAsJsonAsync("api/products", product);
}
else
{
    await http.PutAsJsonAsync("api/products", product);
}

```

**Comment by c0g1t8** [comment]
@M-Yankov 

Oops - I should have tested my code change.  Your suggestion is better and is semantically consistent with the http verb.  I'll make the change and resubmit. 🙏

**Review by c0g1t8 — COMMENTED** [review]
As per suggestion @M-Yankov

**Review by c0g1t8 — COMMENTED** [review]
Bonus fix 😀

**Review by M-Yankov — APPROVED** [review]

**Pull request merged**
